import type { CalculatorDef } from "../types";

export const MATH_DEFS: CalculatorDef[] = [
  {
    slug: "percentage-of",
    category: "math",
    icon: "％",
    title: { en: "Percentage of a Number", ar: "نسبة مئوية من عدد" },
    short: { en: "X% of Y.", ar: "كم يساوي س٪ من ص." },
    description: { en: "Compute X percent of Y.", ar: "احسب س بالمئة من ص." },
    fields: [
      { name: "percent", type: "number", min: -1e12, max: 1e12, label: { en: "Percent", ar: "النسبة" }, suffix: { en: "%", ar: "٪" } },
      { name: "ofValue", type: "number", min: -1e15, max: 1e15, label: { en: "Of value", ar: "من القيمة" } },
    ],
    results: [{ key: "result", label: { en: "Result", ar: "النتيجة" }, format: "number", highlight: true }],
  },
  {
    slug: "percent-change",
    category: "math",
    icon: "📉",
    title: { en: "Percentage Change", ar: "نسبة التغير" },
    short: { en: "Increase or decrease between values.", ar: "الزيادة أو النقصان بين قيمتين." },
    description: { en: "Percent change from an old value to a new one.", ar: "نسبة التغير من قيمة قديمة إلى جديدة." },
    fields: [
      { name: "fromValue", type: "number", label: { en: "From (old)", ar: "من (قديمة)" } },
      { name: "toValue", type: "number", label: { en: "To (new)", ar: "إلى (جديدة)" } },
    ],
    results: [
      { key: "changePct", label: { en: "Change", ar: "التغير" }, format: "percent", highlight: true },
      { key: "difference", label: { en: "Absolute difference", ar: "الفرق المطلق" }, format: "number" },
    ],
  },
  {
    slug: "fraction-simplify",
    category: "math",
    icon: "½",
    title: { en: "Simplify Fraction", ar: "تبسيط الكسر" },
    short: { en: "Lowest terms + decimal.", ar: "أبسط صورة + القيمة العشرية." },
    description: { en: "Reduce a fraction to lowest terms and show its decimal value.", ar: "اختصر الكسر إلى أبسط صورة وأظهر قيمته العشرية." },
    fields: [
      { name: "numerator", type: "integer", min: -1e9, max: 1e9, label: { en: "Numerator", ar: "البسط" } },
      { name: "denominator", type: "integer", min: -1e9, max: 1e9, optional: true, label: { en: "Denominator (default 1)", ar: "المقام (افتراضي 1)" } },
    ],
    results: [
      { key: "simplified", label: { en: "Simplified", ar: "المبسّط" }, format: "raw", highlight: true },
      { key: "decimal", label: { en: "Decimal", ar: "عشريًا" }, format: "number" },
    ],
  },
  {
    slug: "decimal-to-fraction",
    category: "math",
    icon: "⅔",
    title: { en: "Decimal to Fraction", ar: "عشري إلى كسر" },
    short: { en: "Nearest simple fraction.", ar: "أقرب كسر بسيط." },
    description: { en: "Convert a decimal to the closest fraction with denominator ≤ 10,000.", ar: "حوّل عددًا عشريًا إلى أقرب كسر بمقام ≤ 10000." },
    fields: [
      { name: "value", type: "number", min: -1e9, max: 1e9, step: 0.001, label: { en: "Decimal", ar: "العدد العشري" } },
    ],
    results: [
      { key: "fraction", label: { en: "Fraction", ar: "الكسر" }, format: "raw", highlight: true },
      { key: "roundedDecimal", label: { en: "As decimal", ar: "كعدد عشري" }, format: "number" },
    ],
  },
  {
    slug: "gcd-lcm",
    category: "math",
    icon: "🧮",
    title: { en: "GCD & LCM", ar: "القاسم والمضاعف المشترك" },
    short: { en: "Greatest common divisor & least common multiple.", ar: "أكبر قاسم مشترك وأصغر مضاعف مشترك." },
    description: { en: "Compute GCD and LCM of two integers using the Euclidean algorithm.", ar: "احسب القاسم المشترك الأكبر والمضاعف المشترك الأصغر لعددين بخوارزمية إقليدس." },
    fields: [
      { name: "a", type: "integer", min: 0, max: 1e12, label: { en: "First number", ar: "العدد الأول" } },
      { name: "b", type: "integer", min: 0, max: 1e12, label: { en: "Second number", ar: "العدد الثاني" } },
    ],
    results: [
      { key: "gcd", label: { en: "GCD", ar: "القاسم المشترك الأكبر" }, format: "number", highlight: true },
      { key: "lcm", label: { en: "LCM", ar: "المضاعف المشترك الأصغر" }, format: "number" },
    ],
  },
  {
    slug: "prime-check",
    category: "math",
    icon: "🔎",
    title: { en: "Prime Number Check", ar: "فحص الأعداد الأولية" },
    short: { en: "Is n prime? Factor hints.", ar: "هل العدد أولي؟ مع أول عامل." },
    description: { en: "Deterministic primality test by trial division up to √n.", ar: "اختبار أولية حتمي بالقسمة التجريبية حتى الجذر التربيعي." },
    fields: [{ name: "n", type: "integer", min: 0, max: 1e12, label: { en: "Number", ar: "العدد" } }],
    results: [
      { key: "isPrimeLabel", label: { en: "Prime?", ar: "أولي؟" }, format: "raw", highlight: true },
      { key: "smallestFactor", label: { en: "Smallest factor (>1)", ar: "أصغر عامل (>1)" }, format: "number" },
    ],
  },
  {
    slug: "factorial",
    category: "math",
    icon: "❗",
    title: { en: "Factorial", ar: "المضروب" },
    short: { en: "n! for n up to 170.", ar: "مضروب العدد حتى 170." },
    description: { en: "Compute n! — accurate up to 170 in floating point.", ar: "احسب مضروب العدد — دقيق حتى 170 في الفاصلة العائمة." },
    fields: [{ name: "n", type: "integer", min: 0, max: 170, label: { en: "n", ar: "قيمة العدد" } }],
    results: [{ key: "result", label: { en: "n!", ar: "المضروب" }, format: "raw", highlight: true }],
  },
  {
    slug: "quadratic-solver",
    category: "math",
    icon: "𝑥²",
    title: { en: "Quadratic Equation Solver", ar: "حل المعادلة التربيعية" },
    short: { en: "ax² + bx + c = 0.", ar: "حل المعادلة ax² + bx + c = 0." },
    description: { en: "Real or complex roots via the discriminant.", ar: "جذور حقيقية أو مركبة عبر المميز." },
    fields: [
      { name: "a", type: "number", min: -1e9, max: 1e9, label: { en: "a (of x²)", ar: "a (معامل x²)" } },
      { name: "b", type: "number", min: -1e9, max: 1e9, label: { en: "b (of x)", ar: "b (معامل x)" } },
      { name: "c", type: "number", min: -1e9, max: 1e9, label: { en: "c (constant)", ar: "c (الحد الثابت)" } },
    ],
    results: [
      { key: "discriminant", label: { en: "Discriminant", ar: "المميز" }, format: "number" },
      { key: "x1", label: { en: "Root 1", ar: "الجذر الأول" }, format: "raw", highlight: true },
      { key: "x2", label: { en: "Root 2", ar: "الجذر الثاني" }, format: "raw", highlight: false },
    ],
  },
  {
    slug: "stats-summary",
    category: "math",
    icon: "📐",
    title: { en: "Mean / Median / Std Dev", ar: "المتوسط والوسيط والانحراف" },
    short: { en: "Quick statistics for a data set.", ar: "إحصاءات سريعة لمجموعة بيانات." },
    description: { en: "Count, mean, median, min, max and population standard deviation for a list of numbers.", ar: "العدد والمتوسط والوسيط والأدنى والأقصى والانحراف المعياري لقائمة أرقام." },
    fields: [
      {
        name: "numbers",
        type: "text",
        label: { en: "Numbers (comma or space separated)", ar: "الأرقام (مفصولة بفاصلة أو مسافة)" },
        placeholder: "12, 7.5, 3, 21",
      },
    ],
    results: [
      { key: "mean", label: { en: "Mean", ar: "المتوسط" }, format: "number", highlight: true },
      { key: "median", label: { en: "Median", ar: "الوسيط" }, format: "number" },
      { key: "stdDev", label: { en: "Std deviation", ar: "الانحراف المعياري" }, format: "number" },
      { key: "min", label: { en: "Min", ar: "الأدنى" }, format: "number" },
      { key: "max", label: { en: "Max", ar: "الأقصى" }, format: "number" },
      { key: "count", label: { en: "Count", ar: "العدد" }, format: "number" },
    ],
  },
  {
    slug: "random-number",
    category: "math",
    icon: "🎲",
    title: { en: "Random Number Generator", ar: "مولد أرقام عشوائية" },
    short: { en: "Random integers in a range.", ar: "أعداد صحيحة عشوائية في مدى." },
    description: { en: "Generate random integers within [min, max] inclusive.", ar: "أنشئ أعداداً صحيحة عشوائية ضمن المدى الشامل [أدنى، أقصى]." },
    fields: [
      { name: "min", type: "integer", min: -1e9, max: 1e9, label: { en: "Min", ar: "الأدنى" } },
      { name: "max", type: "integer", min: -1e9, max: 1e9, label: { en: "Max", ar: "الأقصى" } },
      { name: "count", type: "integer", min: 1, max: 100, optional: true, label: { en: "How many (default 1)", ar: "الكمية (افتراضي 1)" } },
    ],
    results: [
      { key: "valuesText", label: { en: "Values", ar: "القيم" }, format: "raw", highlight: true },
      { key: "count", label: { en: "Generated", ar: "المولدة" }, format: "number" },
    ],
    note: {
      en: "Seeded PRNG — reproducible when a seed is provided by the API.",
      ar: "مولد ببذرة — قابل للتكرار عند تمرير البذرة من الخادم.",
    },
  },
  {
    slug: "heron-triangle",
    category: "math",
    icon: "🔺",
    title: { en: "Triangle Area (Heron)", ar: "مساحة المثلث (هيرون)" },
    short: { en: "Area from three sides.", ar: "المساحة من ثلاثة أضلاع." },
    description: { en: "Area and perimeter from side lengths using Heron's formula; validates the triangle inequality.", ar: "المساحة والمحيط من أطوال الأضلاع بصيغة هيرون، مع التحقق من متراجحة المثلث." },
    fields: [
      { name: "sideA", type: "number", min: 0.000001, max: 1e9, label: { en: "Side a", ar: "الضلع أ" } },
      { name: "sideB", type: "number", min: 0.000001, max: 1e9, label: { en: "Side b", ar: "الضلع ب" } },
      { name: "sideC", type: "number", min: 0.000001, max: 1e9, label: { en: "Side c", ar: "الضلع ج" } },
    ],
    results: [
      { key: "area", label: { en: "Area", ar: "المساحة" }, format: "number", highlight: true },
      { key: "perimeter", label: { en: "Perimeter", ar: "المحيط" }, format: "number" },
    ],
  },
  {
    slug: "circle",
    category: "math",
    icon: "⭕",
    title: { en: "Circle Calculator", ar: "حاسبة الدائرة" },
    short: { en: "Circumference, area, diameter.", ar: "المحيط والمساحة والقطر." },
    description: { en: "All circle measurements from a radius.", ar: "جميع قياسات الدائرة من نصف القطر." },
    fields: [{ name: "radius", type: "number", min: 0.000001, max: 1e12, label: { en: "Radius", ar: "نصف القطر" } }],
    results: [
      { key: "area", label: { en: "Area", ar: "المساحة" }, format: "number", highlight: true },
      { key: "circumference", label: { en: "Circumference", ar: "المحيط" }, format: "number" },
      { key: "diameter", label: { en: "Diameter", ar: "القطر" }, format: "number" },
    ],
  },
];
